### PR TITLE
Create directories and more output on fail

### PR DESCRIPTION
**Pull request by mjcarroll**
More output to catch #391

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by mjcarroll** [comment]
@j-rivero something weird happening in CI Windows here:

```
# BEGIN SECTION: get open robotics deps (ign-fuel-tools4.yaml) sources into the workspace
Cloning into 'gazebodistro'...
mjcarroll/more_output_on_fail does not match ci_matching_branch/
The system cannot find the drive specified.
branch name mjcarroll/more_output_on_fail is not a match
* master
Input data is not valid format: string indices must be integers, not 'str'
Failed in windows_library with error #1.
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by mjcarroll** [comment]
Waiting on: https://github.com/gazebo-tooling/release-tools/pull/1083 for clean Windows build

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

(I think that the focal and homebrew failures are flakes, they both had timeouts)

**Comment by mjcarroll** [comment]
I think the failures from the last round were network flakes, this should be good to go now.

**Pull request merged**
