### PR TITLE
4 to 7

### PR DESCRIPTION
**Pull request by nkoenig**
# ➡️ Forward port

Port ign-fuel-tools4 (citadel) to ign-fuel-tools7 (fortress)

Branch comparison: [https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>](https://github.com/gazebosim/gz-fuel-tools/compare/ign-fuel-tools7...ign-fuel-tools4)

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by mjcarroll** [comment]
CI seems pretty grumpy about this one.  Missing gz-common?

**Comment by nkoenig** [comment]
> CI seems pretty grumpy about this one. Missing gz-common?

Looks like it needs an ign-common4 release.

**Comment by nkoenig** [comment]
@osrf-jenkins run tests.

**Comment by mjcarroll** [comment]
> Looks like it needs an ign-common4 release.

Pretty sure that the one I just got out should have included those headers, we can see what happens with this run of CI.

**Comment by mjcarroll** [comment]
As discussed in our weekly meeting yesterday, we are still seeing timeouts in the gz_src test and the FuelClient test.

@nkoenig Do you expect those to be resolved with this PR or is there a follow-up coming?

**Comment by nkoenig** [comment]
I have moved the models and worlds under test to the `openroboticstest` organization, and reduced their file size to a few kilobytes. The tests still take an order of magnitude longer on github actions, so I extended the time limit for these test to 500 seconds.

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
